# Generated by Django 6.0.7 on 2026-09-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parser", "0006_telegramchannel_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.JSONField(default=list, verbose_name="Хештеги"),
        ),
    ]
